name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"   # every day at midnight
  workflow_dispatch:        # allows manual run from the Actions tab
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake animation SVG
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: shroukmohamed5
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=#39ff14&color_dots=#0f2247,#ffee00,#ffee00,#ffee00,#ffee00
            dist/github-contribution-grid-snake-dark.svg?color_snake=#39ff14&color_dots=#0f2247,#ffee00,#ffee00,#ffee00,#ffee00

      - name: Push output to "output" branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
